name = "zk-ccvp/cardano"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'zk-ccvp/cardano'"

[repository]
user = "zk-ccvp"
project = "cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
